// English — l'accueil : les textes fixes de index.html, les réglages de la partie,
// la partie à reprendre, l'écran de la langue.
// La clé est la phrase française, ses trous notés {0}, {1}… (voir js/langue.js).
export default {
  "Récoltez, bâtissez, traversez les âges et écrasez l'adversaire — au doigt.": "Gather, build, advance through the ages and crush your opponent — with one finger.",
  "Votre civilisation": "Your civilization",
  "Réglages de la partie": "Game settings",
  "Type de partie": "Game type",
  "Le 2 contre 2 ne compte ni pour le classement ni pour les coffres : ton allié est l'ordinateur.": "2 vs 2 counts neither for ranking nor for chests: your ally is the computer.",
  "Civilisation adverse": "Enemy civilization",
  "Format de partie": "Game mode",
  "Difficulté": "Difficulty",
  "En partie classée, l'adversaire a la force de ta ligue.": "In ranked games, the opponent is as strong as your league.",
  "Taille de la carte": "Map size",
  "Vitesse de jeu": "Game speed",
  "Jouer": "Play",
  "Aide": "Help",
  "<b>Glisser</b> : déplacer la vue · <b>pincer</b> : zoomer": "<b>Drag</b>: move the view · <b>pinch</b>: zoom",
  "<b>Toucher</b> une unité pour la sélectionner, <b>double tap</b> pour toutes celles du même type": "<b>Tap</b> a unit to select it, <b>double tap</b> for all units of the same type",
  "<b>Appui long puis glisser</b> : sélection rectangulaire": "<b>Long press then drag</b>: box selection",
  "Avec une sélection, toucher le sol / un arbre / un ennemi donne l'ordre correspondant": "With units selected, tapping the ground / a tree / an enemy gives the matching order",
  "Vos ouvriers n'abandonnent jamais leur poste tout seuls : la barre des ouvriers, en bas à gauche, montre qui fait quoi et permet de les réaffecter": "Your workers never leave their post on their own: the worker bar, bottom left, shows who does what and lets you reassign them",
  "La partie se sauvegarde toute seule : vous pourrez la reprendre ici même": "The game saves itself: you can pick it up right here",
  "Objectif : ne laisser à l'adversaire ni bâtiment principal ni bâtiment militaire (en mode Express, son bâtiment principal suffit — sinon, au bout du temps, le meilleur score l'emporte)": "Goal: leave the opponent neither a main building nor a military building (in Express mode, the main building is enough — otherwise, when time runs out, the best score wins)",
  "Jeu web autonome : il fonctionne hors ligne une fois chargé. Ta progression est gardée sur cet appareil, et avec ton compte là où la page le permet.": "Standalone web game: it works offline once loaded. Your progress is kept on this device, and with your account where the page allows it.",
  "Le jeu fonctionne sans connexion. Ta progression est gardée sur cet appareil.": "The game works offline. Your progress is kept on this device.",
  "Confidentialité et données": "Privacy and data",
  "Construire": "Build",
  "Affectation des ouvriers": "Worker assignment",
  "Réaffectation automatique": "Automatic reassignment",
  "Quand un gisement s'épuise, l'ouvrier repart seul sur le suivant. Désactivé, il rapporte son chargement puis attend vos ordres.": "When a deposit runs out, the worker moves on to the next one by himself. When off, he brings back his load and then waits for your orders.",
  "Affecter les ouvriers": "Assign workers",
  "Donner une consigne à votre allié": "Give your ally an order",
  "Les positions : à qui elles sont": "The points: who holds them",
  "Lâcher la sélection": "Clear selection",
  "Menu": "Menu",
  "Score : le vôtre, puis celui de l'adversaire": "Score: yours, then your opponent’s",
  "Son": "Sound",
  "Sélectionner toute l'armée": "Select the whole army",
  "Classée": "Ranked",
  "Elo, ligues et coffres": "Elo, leagues and chests",
  "Libre": "Free play",
  "Tu règles l’adversaire": "You set the opponent",
  "Classée · {0}": "Ranked · {0}",
  "Libre · {0}": "Free play · {0}",
  "{0} en face": "vs {0}",
  "carte {0}": "{0} map",
  "vitesse {0}": "speed {0}",
  "Effacer la partie en cours ?": "Erase the game in progress?",
  "Nouvelle partie": "New game",
  "Reprendre la partie": "Resume game",
  "Abandonner cette partie": "Abandon this game",
  "{0} contre {1}": "{0} vs {1}",
  "reste {0}": "{0} left",
  "Partie classée : la quitter compte comme une défaite.": "Ranked game: leaving it counts as a defeat.",
  "Langue": "Language",
  "Le jeu redémarre pour changer de langue. Ta partie en cours est gardée.": "The game restarts to change language. Your game in progress is kept.",
  "Traduction en cours : certains écrans sont encore en français.": "Translation in progress: some screens are still in French.",
  "Choisie": "Selected",
};
