// English — les collections, le blason et les saisons : l'Album, la page d'une
// collection, le blason à composer, la route de la saison et son Passe, le rayon
// des collections de la boutique, les phrases de gains (js/collections-ecrans.js,
// js/blason.js), et les noms de js/collections-config.js (genres, collections,
// autocollants, bannières, cadres, mots de titre, teintures).
// La clé est la phrase française, ses trous notés {0}, {1}… (voir js/langue.js).
//
// Le titre du joueur : un grade, puis une épithète (« Dompteur » + « du Banquet »).
// L'anglais met l'épithète devant (« Banquet Tamer », « Court Jester ») : la clé
// « {grade} {épithète} » inverse donc les deux mots, la suite du titre s'écrit
// « {0} … » et non « … {0} », et « le premier mot » / « la suite » se disent
// « main part » / « front part ». Une épithète anglaise est donc un mot qui se
// met devant un nom (« Barnyard », « Big Freeze »), pas un « of the … ».
// Les noms des autocollants sont des plaisanteries : on a cherché le sourire,
// pas le mot à mot (« Le Général Boulette » → « Major Blunder »).
export default {
  // --- Les mots accordés ---------------------------------------------------------
  "Éclat|Éclats": { one: "Shard", other: "Shards" },
  "Couronne|Couronnes": { one: "Crown", other: "Crowns" },
  // (Passés à l'outil `pluriel` de js/progression-ecrans.js, qui les accorde par `accord` : o.pluriel(n, 'pièce').)
  "pièce|pièces": { one: "piece", other: "pieces" },
  "point|points": { one: "point", other: "points" },

  // --- Ce qui s'écrit partout ----------------------------------------------------
  "environ {0}\u00a0€": "about €{0}",
  "{0} Couronnes": "{0} Crowns",
  "{0} Éclats": "{0} Shards",
  "Éclats": "Shards",
  "À toi": "Yours",
  "Encore : {0}": "Again: {0}",
  "Toucher encore : {0}": "Tap again: {0}",
  "Sauvegarde impossible sur cet appareil : ce ne sera pas retenu.": "Can’t save on this device: this won’t be kept.",
  "et": "and",

  // --- Une pièce dans une phrase -------------------------------------------------
  "le titre «\u00a0{0}\u00a0»": "the title “{0}”",
  "le titre «\u00a0…\u00a0{0}\u00a0»": "the title “{0} …”",
  "l’autocollant «\u00a0{0}\u00a0»": "the sticker “{0}”",
  "l’{0}": "the {0}",
  "la {0}": "the {0}",
  "le {0}": "the {0}",
  "titre «\u00a0{0}\u00a0»": "title “{0}”",
  "titre «\u00a0…\u00a0{0}\u00a0»": "title “{0} …”",
  "un {0}": "a {0}",

  // --- Le titre ------------------------------------------------------------------
  "{grade} {épithète}": "{épithète} {grade}",
  "… {0}": "{0} …",
  "Titre : {0}": "Title: {0}",
  "Titre : … {0}": "Title: {0} …",
  "Titre, le premier mot": "Title, main part",
  "Titre, la suite": "Title, front part",
  "Titre : le premier mot": "Title: main part",
  "Titre : la suite": "Title: front part",

  // --- L'Album -------------------------------------------------------------------
  "Album": "Album",
  "Composer mon blason": "Customize my crest",
  "Toucher pour composer ton blason": "Tap to customize your crest",
  "{0} sur {1}.": "{0} out of {1}.",
  "{0} sur {1} · {2}": "{0} of {1} · {2}",
  "Chaque coffre contient au moins un autocollant ; un doublon devient des Éclats, qui achètent ceux qui te manquent.": "Every chest holds at least one sticker; a duplicate turns into Shards, which buy the ones you’re missing.",
  "Dans les coffres": "In chests",
  "À la boutique": "In the shop",
  "Par les ligues": "From leagues",
  "Route de saison": "Season road",
  "En Éclats": "For Shards",
  "Saison {0}": "Season {0}",

  // --- Une collection ------------------------------------------------------------
  "Porter": "Equip",
  "Porté": "Equipped",
  "Portée": "Equipped",
  "Ses autocollants sortent des coffres.": "Its stickers come from chests.",
  "Il t’en manque {0} : chacun s’achète aussi en Éclats.": "You’re missing {0}: each can also be bought with Shards.",
  "Tu as réuni tous ses autocollants.": "You’ve collected all its stickers.",
  "Ce que la collection donne": "What the collection gives",
  "Un autocollant commun vaut {0} Éclats, un rare {1}, un épique {2}.": "A common sticker costs {0} Shards, a rare one {1}, an epic one {2}.",
  "Les {0} autocollants du jour, à la boutique, sont à moitié prix.": "The {0} stickers of the day, in the shop, are half price.",
  "Une collection de la boutique : ses {0} pièces d’un coup, pour {1} Couronnes{2}.": "A shop collection: all {0} pieces at once, for {1} Crowns{2}.",
  "Cette collection est à toi.": "This collection is yours.",
  "La collection de la saison {0} : elle se gagne palier après palier, sur la route de la saison.": "The season {0} collection: you earn it tier by tier on the season road.",
  "La collection d’une autre saison.": "A collection from another season.",
  "Voir la route": "See the road",
  "Une teinture habille tes troupes d’une autre matière, en partie : l’or et l’acier changent, jamais le tissu de ton camp. Elle ne change rien au combat. Chacune s’achète en Éclats.": "A dye dresses your troops in another material during games: gold and steel change, never your side’s cloth. It changes nothing in combat. Each one is bought with Shards.",
  "Les cadeaux des ligues : ils arrivent à chaque promotion.": "League gifts: they arrive with each promotion.",
  "Et avec elle": "And with it",
  "Ses pièces": "Its pieces",
  "{0} : c’est sur ton blason.": "{0}: it’s on your crest.",
  "{0} : dans ton album.": "{0}: in your album.",
  "Porte-la depuis ton blason pour la voir en partie.": "Equip it from your crest to see it in a game.",
  "La collection te donne {0}.": "The collection gives you {0}.",
  "Il te manque {0} pour cet autocollant.": "You’re {0} short for this sticker.",
  "Il te manque {0} pour cette teinture.": "You’re {0} short for this dye.",
  "Il te manque {0} pour cette collection.": "You’re {0} short for this collection.",
  "{0} : toute la collection est à toi.": "{0}: the whole collection is yours.",

  // --- Le blason -----------------------------------------------------------------
  "Mon blason": "My crest",
  "Mon blason : {0}": "My crest: {0}",
  "Ton blason se voit à l’accueil et à la fin de chaque partie classée. Il ne change rien au combat.": "Your crest shows on the home screen and at the end of every ranked game. It changes nothing in combat.",
  "Teinture des troupes": "Troop dye",
  "Aucun": "None",
  "Rien": "None",
  "Sans teinture : les troupes telles qu’elles sont": "No dye: the troops as they are",
  "Ton premier autocollant t’attend dans un coffre.": "Your first sticker is waiting in a chest.",
  "En partie, l’or et l’acier de tes troupes changent de matière ; le tissu de ton camp ne change jamais.": "In a game, your troops’ gold and steel change material; your side’s cloth never changes.",
  "Les autres teintures": "The other dyes",
  "Voir les teintures": "See the dyes",

  // --- La saison et son Passe ----------------------------------------------------
  "Il reste {0} jours": "{0} days left",
  "Dernier jour": "Last day",
  "Palier {0} sur {1} : la route est finie": "Tier {0} of {1}: the road is complete",
  "Palier {0} sur {1} · {2} sur {3} vers le suivant": "Tier {0} of {1} · {2} out of {3} toward the next",
  "Une partie classée : {0} points. Une victoire : {1} de plus. La première victoire du jour : encore {2}.": "A ranked game: {0} points. A win: {1} more. The first win of the day: another {2}.",
  "Tout prendre ({0})": "Claim all ({0})",
  "Prendre": "Claim",
  "Pris": "Claimed",
  "Pour tous": "For everyone",
  "Passe": "Pass",
  "Passe de saison": "Season Pass",
  "Passe de saison : à toi.": "Season Pass: yours.",
  "Les deux voies sont ouvertes.": "Both tracks are open.",
  "<b>Le Passe de saison</b> ouvre la voie de droite : {0}.": "<b>The Season Pass</b> opens the right-hand track: {0}.",
  "{0} autocollants, {1} pièces de blason (bannière, cadre, deux mots de titre), {2} Couronnes et {3} Éclats": "{0} stickers, {1} crest pieces (banner, frame, two title words), {2} Crowns and {3} Shards",
  "Ni coffre, ni fragment, ni niveau.": "No chests, no fragments, no levels.",
  "Cette collection est déjà passée par ici : tu as {0} de ces pièces. Celles-là te rendront des Éclats à la place ({1} en tout).": "This collection has come around before: you have {0} of these pieces. Those will give you Shards instead ({1} in all).",
  "{0} Couronnes{1}.": "{0} Crowns{1}.",
  "Acheté en cours de saison, il donne aussi les paliers déjà atteints.": "Bought mid-season, it also gives you the tiers you’ve already reached.",
  "Déjà à toi : {0}": "Already yours: {0}",
  "À la fin du mois, les paliers atteints et pas encore pris te sont donnés, puis la saison suivante commence.": "At the end of the month, tiers you’ve reached but not yet claimed are given to you, then the next season begins.",
  "La saison passée est finie, une nouvelle commence.": "Last season is over; a new one begins.",
  "Au-dessus de {0} points, le classement se resserre : ton score repart de {1}, en {2}.": "Above {0} points, the ranking tightens: your score restarts at {1}, in the {2}.",
  "Au-dessus de {0} points, le classement se resserre : ton score repart de {1}.": "Above {0} points, the ranking tightens: your score restarts at {1}.",
  "Tu reçois : {0}.": "You get: {0}.",
  "Il te manque {0} pour le Passe.": "You’re {0} short for the Pass.",
  "Boutique": "Shop",
  "Le Passe de saison est à toi : la voie de droite est ouverte.": "The Season Pass is yours: the right-hand track is open.",

  // --- Les autocollants d'un coffre ----------------------------------------------
  "Doublon : +{0}": "Duplicate: +{0}",
  "Nouveau": "New",
  "Gagné": "Earned",
  "«\u00a0»": "“\u00a0”",
  "dans chaque coffre": "in every chest",

  // --- Le rayon des collections, à la boutique -----------------------------------
  "{0} Éclats, {1} Couronnes : ouvrir la boutique": "{0} Shards, {1} Crowns: open the shop",
  "Saison {0} : {1}": "Season {0}: {1}",
  "{0} Couronnes{1} · ni coffre, ni fragment, ni niveau": "{0} Crowns{1} · no chests, no fragments, no levels",
  "La route": "The road",
  "Voir": "View",
  "Autocollants du jour": "Stickers of the day",
  "Tu as pris tes autocollants du jour. D’autres demain : {0} par jour, à moitié prix, en Éclats.": "You’ve bought today’s stickers. More tomorrow: {0} a day, half price, for Shards.",
  "Il ne te manque aucun autocollant des coffres.": "You’re not missing any chest stickers.",
  "Un autocollant qui te manque : {0} par jour, à moitié prix, en Éclats.": "One sticker you’re missing: {0} a day, half price, for Shards.",
  "{0} autocollants qui te manquent : {1} par jour, à moitié prix, en Éclats.": "{0} stickers you’re missing: {1} a day, half price, for Shards.",
  "Deux": "Two",
  "Trois": "Three",
  "Un autocollant acheté n’est pas remplacé avant demain.": "A sticker you buy isn’t replaced until tomorrow.",
  "Teintures des troupes": "Troop dyes",
  "L’or et l’acier de tes troupes dans une autre matière. En Éclats.": "Your troops’ gold and steel in another material. For Shards.",
  "À porter depuis ton blason.": "Equip it from your crest.",
  "Pour toutes tes troupes": "For all your troops",
  "Collections": "Collections",
  "Une collection entière d’un coup. Tout son contenu est affiché : rien n’y est tiré au sort.": "A whole collection at once. Everything in it is shown: nothing is drawn at random.",
  "Voir la collection : {0}": "View the collection: {0}",
  "{0} autocollants, sa bannière, son cadre et ses deux mots de titre": "{0} stickers, its banner, its frame and its two title words",

  // === Les tables de js/collections-config.js ====================================

  // --- Les genres de pièces ------------------------------------------------------
  "Autocollant": "Sticker",
  "Cadre": "Frame",
  "Bannière": "Banner",
  "Titre": "Title",
  "Teinture": "Dye",

  // --- Les collections -----------------------------------------------------------
  "Le Départ": "The Start",
  "La Basse-cour": "The Barnyard",
  "La Grande Marée": "The High Tide",
  "Les Sables": "The Sands",
  "Le Chantier": "The Construction Site",
  "Les Gaffes de guerre": "War Bloopers",
  "Les Monstres": "The Monsters",
  "Le Banquet": "The Banquet",
  "La Cour": "The Court",
  "Les Ligues": "The Leagues",
  "Les Teintures": "The Dyes",
  "La Nuit des Citrouilles": "Night of the Pumpkins",
  "Le Grand Tournoi": "The Grand Tournament",
  "Le Grand Froid": "The Big Freeze",

  // --- Le Départ -----------------------------------------------------------------
  "Villageois": "Villager",
  "Bannière de papier": "Paper Banner",
  "Cadre simple": "Plain Frame",

  // --- La Basse-cour -------------------------------------------------------------
  "Cochon couronné": "Crowned Pig",
  "Poule guerrière": "Warrior Hen",
  "Mouton volant": "Flying Sheep",
  "Cerf à lunettes": "Deer in Shades",
  "Âne chargé d’or": "Gold-Laden Donkey",
  "Chèvre du rempart": "Rampart Goat",
  "Canard amiral": "Admiral Duck",
  "Cochon chevalier": "Sir Oinks-a-Lot",
  "Le Roi des cochons": "The Pig King",
  "Fermier": "Farmer",
  "Bannière de la Basse-cour": "Barnyard Banner",
  "Cadre de la Basse-cour": "Barnyard Frame",
  "de la Basse-cour": "Barnyard",

  // --- La Grande Marée -----------------------------------------------------------
  "Crabe garde du corps": "Bodyguard Crab",
  "Poisson bouffon": "Jesterfish",
  "Méduse lanterne": "Lantern Jellyfish",
  "Bernard propriétaire": "Hermit Homeowner",
  "Étoile en vacances": "Starfish on Vacation",
  "Poulpe forgeron": "Octopus Blacksmith",
  "Hippocampe de course": "Racing Seahorse",
  "Tortue forteresse": "Fortress Turtle",
  "Requin couronné": "Crowned Shark",
  "Amiral": "Admiral",
  "Bannière des Sept Mers": "Seven Seas Banner",
  "Cadre des Sept Mers": "Seven Seas Frame",
  "des Sept Mers": "Seven Seas",

  // --- Les Sables ----------------------------------------------------------------
  "Dromadaire à lunettes": "Camel in Shades",
  "Scarabée du soleil": "Sun Scarab",
  "Cactus boxeur": "Boxing Cactus",
  "Momie emmêlée": "Tangled Mummy",
  "Fennec curieux": "Curious Fennec",
  "Chat pharaon": "Pharaoh Cat",
  "Crocodile à bouée": "Crocodile in a Floatie",
  "Scorpion barbier": "Barber Scorpion",
  "Sphinx qui bâille": "Yawning Sphinx",
  "Pharaon": "Pharaoh",
  "Bannière des Sables": "Sands Banner",
  "Cadre des Sables": "Sands Frame",
  "des Sables": "Desert",

  // --- Le Chantier ---------------------------------------------------------------
  "Villageois endormi": "Napping Villager",
  "Brouette de course": "Racing Wheelbarrow",
  "Seau percé": "Leaky Bucket",
  "Navet géant": "Giant Turnip",
  "Casse-croûte": "Snack Break",
  "L’Arbre têtu": "The Stubborn Tree",
  "Pépite géante": "Giant Nugget",
  "Maison de travers": "Crooked House",
  "Le Grand Architecte": "The Great Architect",
  "Contremaître": "Foreman",
  "Bannière du Chantier": "Construction Site Banner",
  "Cadre du Chantier": "Construction Site Frame",
  "du Chantier": "Construction Site",

  // --- Les Gaffes de guerre ------------------------------------------------------
  "Flèche ventouse": "Suction-Cup Arrow",
  "Carte à l’envers": "Upside-Down Map",
  "Bouclier marmite": "Pot-Lid Shield",
  "Lance tordue": "Bent Spear",
  "Drapeau blanc": "White Flag",
  "Bélier coincé": "Stuck Battering Ram",
  "Chevalier à l’envers": "Backward Knight",
  "Catapulte à cochon": "Pig Catapult",
  "Le Général Boulette": "Major Blunder",
  "Maladroit": "Klutz",
  "Bannière des Gaffes": "Blooper Banner",
  "Cadre des Gaffes": "Blooper Frame",
  "des Gaffes": "Blooper",

  // --- Les Monstres --------------------------------------------------------------
  "Dragon enrhumé": "Sniffly Dragon",
  "Cyclope myope": "Nearsighted Cyclops",
  "Kraken tricoteur": "Knitting Kraken",
  "Griffon facteur": "Mailman Griffin",
  "Minotaure perdu": "Lost Minotaur",
  "Sirène rockeuse": "Rock Star Mermaid",
  "Phénix frileux": "Shivering Phoenix",
  "Sphinx aux énigmes": "Puzzled Sphinx",
  "L’Hydre aux trois glaces": "The Three-Scoop Hydra",
  "Dompteur": "Tamer",
  "Bannière des Monstres": "Monster Banner",
  "Cadre des Monstres": "Monster Frame",
  "des Monstres": "Monster",

  // --- Le Banquet ----------------------------------------------------------------
  "Jambon royal": "Royal Ham",
  "Fromage fortifié": "Fortified Cheese",
  "Tarte aux baies": "Berry Pie",
  "Poisson évadé": "Runaway Fish",
  "Pain bouclier": "Bread Shield",
  "Marmite magique": "Magic Pot",
  "Gâteau château": "Castle Cake",
  "Chef moustachu": "Mustachioed Chef",
  "Le Grand Festin": "The Great Feast",
  "Gourmand": "Foodie",
  "Bannière du Banquet": "Banquet Banner",
  "Cadre du Banquet": "Banquet Frame",
  "du Banquet": "Banquet",

  // --- La Cour -------------------------------------------------------------------
  "Roi grenouille": "Frog King",
  "Couronne trop grande": "Crown Too Big",
  "Bouffon jongleur": "Juggling Jester",
  "Trompette nouée": "Knotted Trumpet",
  "Trône de sable": "Sandcastle Throne",
  "Le Chat du trône": "The Throne Cat",
  "Reine des abeilles": "Queen Bee",
  "Empereur manchot": "Penguin Emperor",
  "Le Portrait officiel": "The Official Portrait",
  "Bouffon": "Jester",
  "Bannière de la Cour": "Court Banner",
  "Cadre de la Cour": "Court Frame",
  "de la Cour": "Court",

  // --- Les Ligues ----------------------------------------------------------------
  "Recrue": "Recruit",
  "Bannière de Bronze": "Bronze Banner",
  "Bannière de Fer": "Iron Banner",
  "Capitaine": "Captain",
  "Cadre d’Or": "Gold Frame",
  "Stratège": "Strategist",
  "Cadre d’Orichalque": "Orichalcum Frame",
  "Empereur": "Emperor",
  "Légende": "Legend",
  "Cadre des Légendes": "Legends Frame",

  // --- Les Teintures -------------------------------------------------------------
  "Teinture d’argent": "Silver Dye",
  "Teinture de jade": "Jade Dye",
  "Teinture d’obsidienne": "Obsidian Dye",
  "Teinture d’améthyste": "Amethyst Dye",

  // --- La Nuit des Citrouilles ---------------------------------------------------
  "Citrouille casquée": "Helmeted Pumpkin",
  "Fantôme du villageois": "Ghost Villager",
  "Chauve-souris messagère": "Messenger Bat",
  "Chat de minuit": "Midnight Cat",
  "Épouvantail lancier": "Scarecrow Spearman",
  "Coffre à bonbons": "Candy Chest",
  "Araignée au hamac": "Hammock Spider",
  "Squelette archer": "Skeleton Archer",
  "Chaudron gourmand": "Hungry Cauldron",
  "Loup-garou frileux": "Shivering Werewolf",
  "Sorcière au bélier": "Ram-Riding Witch",
  "Vampire à la tomate": "Tomato Juice Vampire",
  "Citrouille catapultée": "Catapulted Pumpkin",
  "Hibou veilleur": "Night-Watch Owl",
  "Lanterne navet": "Jack-o’-Turnip",
  "L’Hydre fantôme": "The Ghost Hydra",
  "Le Pharaon citrouille": "The Pumpkin Pharaoh",
  "La Reine de la Nuit": "The Queen of the Night",
  "Croque-citrouille": "Gourd Gobbler",
  "Bannière des Citrouilles": "Pumpkin Banner",
  "Cadre des Citrouilles": "Pumpkin Frame",
  "des Citrouilles": "Pumpkin",
  "Étendard de la Nuit": "Night Pennant",
  "Épouvantail en chef": "Scarecrow-in-Chief",

  // --- Le Grand Tournoi ----------------------------------------------------------
  "Chevalier en pantoufles": "Knight in Slippers",
  "Lance en mousse": "Foam Lance",
  "Cheval de bois": "Rocking Horse",
  "Écuyer débordé": "Swamped Squire",
  "Heaume à plume": "Plumed Helm",
  "Bouclier troué": "Holey Shield",
  "Jouteur désarçonné": "Unhorsed Jouster",
  "Mouchoir géant": "Giant Hanky",
  "Héraut essoufflé": "Winded Herald",
  "Cochon de joute": "Jousting Pig",
  "Tribune en folie": "Crowd Gone Wild",
  "Trophée trop lourd": "Trophy Too Heavy",
  "Arbitre au sablier": "Hourglass Referee",
  "Duel de dromadaires": "Camel Duel",
  "Triton jouteur": "Jousting Merman",
  "Le Champion masqué": "The Masked Champion",
  "La Coupe d’Orichalque": "The Orichalcum Cup",
  "Le Roi du Tournoi": "The Tournament King",
  "Jouteur": "Jouster",
  "Bannière du Tournoi": "Tournament Banner",
  "Cadre du Tournoi": "Tournament Frame",
  "du Tournoi": "Tournament",
  "Étendard du Tournoi": "Tournament Pennant",
  "Roi de la joute": "Joust King",

  // --- Le Grand Froid ------------------------------------------------------------
  "Bonhomme de garde": "Snowman-at-Arms",
  "Manchot glisseur": "Sliding Penguin",
  "Villageois emmitouflé": "Bundled-Up Villager",
  "Chocolat chaud": "Hot Cocoa",
  "Luge de combat": "Battle Sled",
  "Moufles géantes": "Giant Mittens",
  "Sapin de caserne": "Barracks Fir Tree",
  "Dromadaire frileux": "Shivering Camel",
  "Triton patineur": "Skating Merman",
  "Ours câlin": "Bear Hug",
  "Sphinx en glaçon": "Sphinx on the Rocks",
  "Yéti timide": "Shy Yeti",
  "Renne éclaireur": "Reindeer Scout",
  "Igloo fortifié": "Fortified Igloo",
  "La Trêve du feu": "The Fireside Truce",
  "L’Hydre enrhumée": "The Sneezy Hydra",
  "Le Roi des Neiges": "The Snow King",
  "Le Grand Traîneau": "The Great Sleigh",
  "Frileux": "Shiverer",
  "Bannière du Grand Froid": "Big Freeze Banner",
  "Cadre du Grand Froid": "Big Freeze Frame",
  "du Grand Froid": "Big Freeze",
  "Étendard du Grand Froid": "Big Freeze Pennant",
  "Maître des neiges": "Snow Master",
};
