// English — l'écran de jeu (js/ui.js) : panneau de sélection, commandes, menus de
// construction et d'ouvriers, consignes à l'allié, menu de pause, aide, crédits,
// écran de fin de partie.
// La clé est la phrase française, ses trous notés {0}, {1}… (voir js/langue.js).
// Les phrases des crédits écrites sur plusieurs lignes dans js/ui.js gardent leurs
// retours à la ligne dans la clé (« \n » et le retrait) : le français ne bouge pas.
export default {
  // --- Les réglages repliés de l'accueil (resumeReglages) ---
  "{0} en face": "vs {0}",
  "carte {0}": "{0} map",
  "vitesse {0}": "speed {0}",

  // --- Les consignes à l'allié : ce qu'il en fait ---
  "Votre allié est hors de combat": "Your ally is out of the fight",
  "Votre allié est attaqué chez lui : il repousse d’abord l’ennemi": "Your ally is under attack at home and is pushing the enemy back first",
  "Votre allié n’a aucun soldat au camp : il attend d’en avoir, 2 minutes au plus": "Your ally has no soldiers in camp: waiting for some, 2 minutes at most",
  "soldat|soldats": { one: "soldier", other: "soldiers" },
  "Votre allié envoie {0} {1} vous défendre": "Your ally is sending {0} {1} to defend you",
  "Votre allié envoie {0} {1} à l’attaque": "Your ally is sending {0} {1} to attack",

  // --- Le panneau des ouvriers ---
  "Nourriture": "Food",
  "buissons et fermes": "bushes and farms",
  "Bois": "Wood",
  "forêts": "forests",
  "Or": "Gold",
  "filons": "gold veins",
  "Chantiers": "Construction sites",
  "chantier ouvert|chantiers ouverts": { one: "site open", other: "sites open" },
  "aucun chantier ouvert": "no site open",
  "Sans affectation": "Unassigned",
  "en attente d’ordres": "awaiting orders",
  "{0} en déplacement": "{0} on the move",
  "{0} à l’abri": "{0} sheltered",

  // --- Le panneau de sélection ---
  "Touchez une unité pour la sélectionner · appui long pour un rectangle": "Tap a unit to select it · long press for a box",
  "{0} de nourriture": "{0} food",
  "sauvage — approchez un {0}": "wild — bring a {0} close",
  "gibier — envoyez des {0}": "wild game — send {0}",
  "capturé — un {0} l’abat": "captured — a {0} slaughters it",
  "{0} chantier(s) en file": "{0} site(s) queued",
  "portée {0}": "range {0}",
  "{0} %": "{0}%",
  "ouvrier|ouvriers": { one: "worker", other: "workers" },
  "aucun ouvrier — touchez le chantier avec des {0}": "no worker — select {0} and tap the site",
  "(sauvage)": "(wild)",
  "(allié)": "(ally)",
  "(ennemi)": "(enemy)",
  "{0} unités sélectionnées": "{0} units selected",
  "Annuler": "Cancel",

  // --- Les commandes ---
  "Stop": "Stop",
  "Construire": "Build",
  "Attaquer ici": "Attack here",
  "Abriter": "Shelter",
  "+1 ouvrier": "+1 worker",
  "Aucun {0} disponible": "No {0} available",
  "Confirmer": "Confirm",
  "{0} : troupe à débloquer — vois « Troupes » à l’accueil": "{0}: troop to unlock — see “Troops” on the home screen",
  "Cloche": "Bell",
  "Libérer ({0})": "Release ({0})",
  "Personne à l’intérieur": "Nobody inside",
  "Ralliement": "Rally point",
  "Détruire": "Destroy",
  "Indisponible": "Unavailable",

  // --- Le menu de construction ---
  "Nécessite : {0}": "Requires: {0}",
  "Nombre maximum atteint": "Maximum number reached",
  "Ressources insuffisantes": "Not enough resources",

  // --- Le menu de pause : personnages 3D, finesse, mesures ---
  "Tes personnages 3D se préparent (au premier lancement seulement) : les dessins servent en attendant.": "Your 3D characters are getting ready (first launch only): the drawings stand in meanwhile.",
  "Tes personnages 3D sont prêts, mais allégés faute de mémoire ({0}) : ils paraissent plus flous. Ferme les autres onglets puis relance le jeu.": "Your 3D characters are ready, but slimmed down for lack of memory ({0}): they look blurrier. Close your other tabs, then restart the game.",
  "Tes personnages 3D sont prêts, à pleine finesse.": "Your 3D characters are ready, at full sharpness.",
  "Tes personnages 3D n’ont pas pu se préparer sur cet appareil ({0}) : les dessins les remplacent.": "Your 3D characters could not be prepared on this device ({0}): the drawings replace them.",
  "{0} pixel{1} par point": "{0} px per point",
  "Affichée : {0}, toute la finesse de cet écran.": "Displayed: {0}, the full sharpness of this screen.",
  "Affichée : {0} au lieu de {1} — imposée par « ?dpr= » dans l’adresse.": "Displayed: {0} instead of {1} — forced by “?dpr=” in the address.",
  "Affichée : {0} au lieu de {1} — c’est ton réglage « Légère ».": "Displayed: {0} instead of {1} — that’s your “Light” setting.",
  "Affichée : {0} au lieu de {1} — réduite automatiquement, le jeu ralentissait.": "Displayed: {0} instead of {1} — lowered automatically, the game was slowing down.",
  "Affichée : {0} au lieu de {1}.": "Displayed: {0} instead of {1}.",
  "{0} images par seconde": "{0} frames per second",
  "cadence pas encore mesurée": "frame rate not measured yet",
  "Mesures : {0} · {1} Mo d’images de troupes ({2} {3} en mémoire) · {4}.": "Stats: {0} · {1} MB of troop images ({2} {3} in memory) · {4}.",
  "troupe|troupes": { one: "troop", other: "troops" },
  "Dernier rechargement en pleine partie": "Last reload in mid-game",
  "Dernière coupure relevée": "Last interruption recorded",
  " ({0} incidents en tout)": " ({0} incidents in all)",
  "{0} {1} : le {2}, {3}{4}.": "{0} {1}: {2}, {3}{4}.",

  // --- Les consignes à l'allié : la fenêtre ---
  "Votre allié": "Your ally",
  "Il joue seul. Une consigne lui dit quoi faire de ses soldats, une fois ; ensuite il reprend sa conduite.": "Your ally plays on its own. An order tells it what to do with its soldiers, once; then it goes back to its own plan.",
  "Attaque ici": "Attack here",
  "Touchez ensuite l'endroit sur la carte : ses soldats y marchent.": "Then tap the spot on the map: its soldiers march there.",
  "Défends-moi": "Defend me",
  "Ses soldats viennent tenir votre {0} 3 minutes.": "Its soldiers come and hold your {0} for 3 minutes.",
  "À toi de voir": "Your call",
  "Il rappelle ses soldats et fait comme il l'entend.": "It calls its soldiers back and does as it sees fit.",
  "Fermer": "Close",

  // --- Le menu de pause ---
  "Fine": "Sharp",
  "Tous les pixels de l’écran": "Every pixel of the screen",
  "Légère": "Light",
  "Si le jeu rame ou chauffe": "If the game lags or runs hot",
  "Oui": "Yes",
  "Elle change quand un combat commence": "It changes when a fight starts",
  "Non": "No",
  "Les bruitages seuls": "Sound effects only",
  "Partie en pause": "Game paused",
  "La partie est sauvegardée : vous pouvez fermer l'onglet et la reprendre plus tard.": "The game is saved: you can close the tab and pick it up later.",
  "Vitesse de jeu": "Game speed",
  "Style des personnages": "Character style",
  "Finesse de l’image": "Image sharpness",
  "Musique": "Music",
  "Reprendre": "Resume",
  "Comment jouer": "How to play",
  "Crédits": "Credits",
  "Confidentialité": "Privacy",
  "Abandonner": "Resign",

  // --- L'aide ---
  "<b>Glisser</b> : déplacer la vue · <b>pincer</b> : zoomer": "<b>Drag</b>: move the view · <b>pinch</b>: zoom",
  "<b>Toucher</b> une unité : la sélectionner · <b>double tap</b> : toutes les unités du même type visibles": "<b>Tap</b> a unit: select it · <b>double tap</b>: all visible units of the same type",
  "<b>Appui long puis glisser</b> : sélection rectangulaire": "<b>Long press then drag</b>: box selection",
  "<b>{0} Armée</b>, au bout de la barre des ouvriers : un toucher prend tous vos soldats, où qu'ils soient ; un second amène la vue sur eux. La <b>{1} croix</b> du panneau lâche la sélection": "<b>{0} Army</b>, at the end of the worker bar: one tap selects all your soldiers, wherever they are; a second brings the view to them. The panel’s <b>{1} cross</b> clears the selection",
  "<b>« Vous êtes attaqué ! »</b> : touchez le message pour aller voir ; l'endroit pulse en rouge sur la mini-carte": "<b>“You are under attack!”</b>: tap the message to go and see; the spot pulses red on the minimap",
  "Avec une sélection, <b>toucher</b> le sol, un arbre, une mine ou un ennemi donne l'ordre correspondant. Un appui au sol se suit jusqu'au bout, même en plein combat : c'est le geste pour replier vos troupes": "With units selected, <b>tapping</b> the ground, a tree, a mine or an enemy gives the matching order. A tap on the ground is followed all the way, even in mid-fight: that’s how you pull your troops back",
  "<b>Réparer</b> : des {0} sélectionnés, touchez un de vos bâtiments abîmés. <b>Soigner</b> : sélectionnez votre {1}, puis touchez un allié blessé. (Double tap pour sélectionner à la place.)": "<b>Repair</b>: with {0} selected, tap one of your damaged buildings. <b>Heal</b>: select your {1}, then tap a wounded ally. (Double tap to select instead.)",
  "<b>{0} Construire</b> : choisissez un bâtiment, puis touchez l'emplacement. Les {1} sélectionnés s'y mettent <b>tous</b> — à plusieurs, ça va bien plus vite. Enchaînez les poses : elles se mettent <b>en file</b> et l'ouvrier passe à la suivante en terminant": "<b>{0} Build</b>: pick a building, then tap the spot. <b>All</b> the selected {1} get to work on it — together, it goes much faster. Place several in a row: they <b>queue up</b> and the worker moves on to the next one when done",
  "<b>Affecter quelqu'un à un chantier</b> : touchez un {0}, puis touchez le chantier — le même geste que pour l'envoyer au bois ou à la nourriture. La ligne <b>{1} Chantiers</b> de la barre <b>{2} Ouvriers</b> fait pareil avec ses <b>+ / −</b>, et un chantier sélectionné a son bouton <b>{3} +1 ouvrier</b>. (Double tap sur un chantier pour le sélectionner sans y envoyer personne.)": "<b>Assign someone to a construction site</b>: tap a {0}, then tap the site — just like sending him to gather wood or food. The <b>{1} Construction sites</b> row of the <b>{2} Workers</b> bar does the same with its <b>+ / −</b>, and a selected site has its <b>{3} +1 worker</b> button. (Double tap a site to select it without sending anyone.)",
  "Les {0} récoltent {1} nourriture, {2} bois et {3} or ; il faut des <b>maisons</b> pour agrandir la population": "Your {0} gather {1} food, {2} wood and {3} gold; you need <b>houses</b> to raise the population",
  "<b>Attitudes</b> (unité sélectionnée) : {0} agressif poursuit loin, {1} défensif revient à son poste, {2} position tenue ne bouge pas, {3} sans attaque ignore l'ennemi": "<b>Stances</b> (unit selected): {0} aggressive chases far, {1} defensive returns to its post, {2} stand ground does not move, {3} no attack ignores the enemy",
  "<b>Garnison</b> : des soldats sélectionnés s'abritent d'un appui sur votre {0} ou une tour ; des {1}, par le bouton <b>{2} Abriter</b> puis l'abri. Les occupants s'y soignent et chacun ajoute une flèche. La <b>{3} cloche</b> y envoie tous les {4} d'un coup ; un second coup renvoie chacun à son poste": "<b>Garrison</b>: selected soldiers take shelter with a tap on your {0} or a tower; {1}, with the <b>{2} Shelter</b> button then the shelter. Those inside heal, and each one adds an arrow. The <b>{3} bell</b> sends all your {4} inside at once; a second ring sends everyone back to their post",
  "<b>C'est vous qui affectez vos ouvriers</b> : quand un gisement s'épuise, le {0} rapporte son chargement puis attend vos ordres. La barre <b>{1} Ouvriers</b> montre qui fait quoi et permet de réaffecter d'un doigt": "<b>You assign your workers yourself</b>: when a deposit runs out, the {0} brings back his load, then waits for your orders. The <b>{1} Workers</b> bar shows who does what and lets you reassign with one finger",
  "Passez les <b>âges</b> depuis le {0} pour débloquer de nouvelles unités": "Advance through the <b>ages</b> from the {0} to unlock new units",
  "<b>Vitesse de jeu</b> : réglable ici même (Tranquille à Blitz ×2) — et depuis l'écran d'accueil": "<b>Game speed</b>: set it right here (Relaxed to Blitz ×2) — or from the home screen",
  "<b>La partie se sauvegarde toute seule</b> toutes les 30 s et dès que vous quittez l'onglet : vous la retrouverez sur l'écran d'accueil, bouton <b>Reprendre</b>": "<b>The game saves itself</b> every 30 s and as soon as you leave the tab: you’ll find it on the home screen, <b>Resume game</b> button",
  "<b>Objectif</b> : ne laisser à l'adversaire ni {0} ni bâtiment militaire ({1}), achevé ou en chantier — inutile de raser la dernière ferme. En {2} Escarmouche, en {3} Express et en {4} Prise de positions, son dernier {5} suffit ; sinon, au bout du temps, le meilleur score l'emporte": "<b>Goal</b>: leave the opponent neither a {0} nor a military building ({1}), finished or under construction — no need to raze the last farm. In {2} Skirmish, {3} Express and {4} Capture Points, its last {5} is enough; otherwise, when time runs out, the best score wins",
  "<b>{0} Positions</b> : {1} monuments sur la ligne du milieu, chacun dans son cercle. Tenez des <b>soldats</b> dans le cercle pendant {2} secondes, sans soldat adverse dedans, et la position est à vous — elle le reste même si vous partez, jusqu'à ce que l'adversaire la reprenne. Chaque position tenue rapporte <b>1 point toutes les {3} secondes</b> ; le premier à <b>{4} points</b> gagne. Les losanges en haut de l'écran et sur la mini-carte disent à qui elles sont": "<b>{0} Capture points</b>: {1} monuments on the middle line, each in its circle. Keep <b>soldiers</b> in the circle for {2} seconds, with no enemy soldier inside, and the point is yours — it stays yours even if you leave, until the opponent takes it back. Each point held earns <b>1 point every {3} seconds</b>; the first to <b>{4} points</b> wins. The diamonds at the top of the screen and on the minimap show who holds them",
  "<b>Score</b> {0} : la moitié de ce que vous récoltez, le prix de vos troupes et bâtiments encore debout, et deux fois le prix de ce que vous abattez. Il s'affiche en haut, à côté du chrono : le vôtre, puis celui de l'adversaire": "<b>Score</b> {0}: half of what you gather, the cost of your troops and buildings still standing, and twice the cost of what you take down. It shows at the top, next to the clock: yours, then your opponent’s",
  "J'ai compris": "Got it",

  // --- Les crédits ---
  "<b>Icônes</b> — {0},\n          sous licence {1}.": "<b>Icons</b> — {0}, under the {1} license.",
  "<b>Illustrations</b> (personnages, bâtiments, arbres, décor, textures de sol et\n          d'eau, coffres, autocollants des collections) — générées par l'auteur du jeu, puis\n          découpées et détourées pour le jeu.": "<b>Illustrations</b> (characters, buildings, trees, scenery, ground and water textures, chests, collection stickers) — generated by the game’s author, then cut out and trimmed for the game.",
  "<b>Chevalier, villageois, archer, lancier, Atlante, Champion, Arbalétrier, Archer monté, Éclaireur, Cavalier, Bélier, Catapulte, Prêtresse et Hydre 3D ; Fellah, Garde, Lancier, Archer, Arbalétrier, Archer monté, Chacal dressé, Méhariste, Garde masqué, Prêtre du Soleil et Sphinx des Solariens</b> — modèles et animations de l'auteur du\n          jeu, faits dans son Atelier 3D ; icônes du trident, de l'Hydre et du Temple dessinées pour le jeu ; cuits par\n          {0} (licence MIT).": "<b>3D Militiaman, Villager, Archer, Spearman, Atlantean, Champion, Crossbowman, Horse Archer, Scout, Knight, Battering Ram, Catapult, Priestess and Hydra; the Solarians’ Fellah, Guard, Spearman, Archer, Crossbowman, Horse Archer, Trained Jackal, Camel Rider, Masked Guard, Sun Priest and Sphinx</b> — models and animations by the game’s author, made in his 3D Workshop; trident, Hydra and Temple icons drawn for the game; baked by {0} (MIT license).",
  "<b>Chevalier 3D d'essai</b> (styles « 3D précalculée » et « 3D en direct ») — KayKit Adventurers, par\n          {0},\n          domaine public (CC0) ; rendu en direct par\n          {1} (licence MIT).": "<b>Trial 3D knight</b> (“Pre-rendered 3D” and “Live 3D” styles) — KayKit Adventurers, by {0}, public domain (CC0); rendered live by {1} (MIT license).",
  "<b>Bruitages</b> — paquets audio de {0}, domaine public (CC0).": "<b>Sound effects</b> — audio packs by {0}, public domain (CC0).",
  "<b>Musique</b> — « Minstrel Dance » et « Harvest Season » de RandomMind, « Determined Pursuit » d'Emma_MA,\n          publiés sur {0}, domaine public (CC0).": "<b>Music</b> — “Minstrel Dance” and “Harvest Season” by RandomMind, “Determined Pursuit” by Emma_MA, published on {0}, public domain (CC0).",
  "<b>Caractères</b> — « Lilita One » de Juan Montoreano et « Nunito » de The Nunito Project Authors,\n          sous licence {0}.": "<b>Fonts</b> — “Lilita One” by Juan Montoreano and “Nunito” by The Nunito Project Authors, under the {0}.",
  "<b>Jeu</b> — inspiré des classiques de la stratégie en temps réel, sans en\n          reprendre aucun contenu.": "<b>Game</b> — inspired by the classics of real-time strategy, without reusing any of their content.",

  // --- La fin de partie : ce qui a tranché ---
  "Les deux camps atteignent {0} points ensemble, en {1}": "Both sides reach {0} points together, in {1}",
  "Vous tenez les positions : {0} points atteints en {1}": "You hold the capture points: {0} points reached in {1}",
  "L’adversaire a tenu les positions : {0} points atteints en {1}": "The opponent held the capture points: {0} points reached in {1}",
  "Temps écoulé après {0} — les points des positions départagent": "Time’s up after {0} — the capture point scores decide",
  "Temps écoulé après {0} — la somme des scores de chaque équipe départage": "Time’s up after {0} — each team’s total score decides",
  "Temps écoulé après {0} — le score départage": "Time’s up after {0} — the score decides",
  "Vous avez abandonné après {0}": "You resigned after {0}",
  "Durée de la partie : {0}": "Game length: {0}",
  "Les deux bâtiments principaux adverses sont tombés en {0}": "Both enemy main buildings fell in {0}",
  "Votre équipe n’a plus de bâtiment principal — durée de la partie : {0}": "Your team has no main building left — game length: {0}",
  "{0} {1} adverse est tombé{2} en {3}": "The enemy {1} fell in {3}",
  "Votre {0} est tombé{1} — durée de la partie : {2}": "Your {0} fell — game length: {2}",
  "L’adversaire n’a plus ni {0} ni bâtiment militaire — durée de la partie : {1}": "The opponent has neither a {0} nor a military building left — game length: {1}",
  "Vous n’avez plus ni {0} ni bâtiment militaire — durée de la partie : {1}": "You have neither a {0} nor a military building left — game length: {1}",

  // --- La fin de partie : le palmarès ---
  "<b>Nouveau record !</b> Victoire en {0} — le précédent était de {1}": "<b>New record!</b> Victory in {0} — the previous one was {1}",
  "<b>Premier temps au palmarès :</b> victoire en {0}": "<b>First time on record:</b> victory in {0}",
  "Meilleur temps à battre : {0}": "Best time to beat: {0}",
  "<b>Nouveau record !</b> {0} points — le précédent était de {1}": "<b>New record!</b> {0} points — the previous one was {1}",
  "<b>Premier score au palmarès :</b> {0} points": "<b>First score on record:</b> {0} points",
  "Meilleur score à battre : {0} points": "Best score to beat: {0} points",
  "{0} · {1} : {2} {3}, {4} {5}": "{0} · {1}: {2} {3}, {4} {5}",
  "victoire|victoires": { one: "win", other: "wins" },
  "défaite|défaites": { one: "loss", other: "losses" },

  // --- La fin de partie : l'écran ---
  "Égalité": "Draw",
  "Victoire !": "Victory!",
  "Défaite": "Defeat",
  "Vous": "You",
  "Adversaire": "Opponent",
  "Adv.": "Opp.",
  "Bâtiment principal": "Main building",
  "tombé": "fallen",
  "debout": "standing",
  "Unités formées": "Units trained",
  "Unités perdues": "Units lost",
  "Score": "Score",
  "Par équipe": "Per team",
  "Au bout du temps, la somme des scores de chaque équipe départage.": "When time runs out, each team’s total score decides.",
  "Ressources récoltées": "Resources gathered",
  "Bâtiments construits": "Buildings built",
  "Âge atteint": "Age reached",
  "Points de récolte": "Gathering points",
  "Troupes et bâtiments debout": "Troops and buildings standing",
  "Ennemis abattus": "Enemies taken down",
  "Points des positions": "Capture point score",
  "Score final": "Final score",
  "Score : un point toutes les {0} secondes par position tenue.": "Score: one point every {0} seconds per point held.",
  "Score : la moitié des ressources récoltées, le prix de ce qui est encore debout, et deux fois le prix de ce qui a été abattu chez l’autre.": "Score: half the resources gathered, the cost of what is still standing, and twice the cost of what was taken down on the other side.",
  "Nouvelle partie": "New game",
  "Menu principal": "Main menu",
};
