// English — la partie : les alertes et les messages du déroulement (js/main.js),
// ce que la simulation dit au joueur (js/game.js, js/ai.js), le palmarès et les
// incidents (js/save.js), les styles des personnages et leurs modèles 3D
// (js/sprites.js, js/modele3d.js).
// La clé est la phrase française, ses trous notés {0}, {1}… (voir js/langue.js).
// Un trou qui ne porte qu'un accord français (« terminé{1} », « {2} {3} » pour
// « une Caserne ») est laissé de côté par la traduction.
export default {
  // --- js/main.js : le début de la partie, les réglages d'image ---
  "Affectez vos {0} : touchez-les, puis touchez un arbre, un buisson ou un filon.": "Put your {0} to work: tap them, then tap a tree, a bush or a gold vein.",
  "Partie d’essai : {0} {1} t’attendent près de ton centre.": "Trial game: {0} {1} are waiting for you near your main building.",
  "Image légère : deux pixels par point": "Light image: two pixels per point",
  "Image fine : tous les pixels de l’écran": "Sharp image: every pixel on the screen",

  // --- js/main.js : ce qui arrive pendant la partie ---
  "{0} terminé{1}": "{0} complete",
  "{0} {1} attendent vos ordres": "{0} {1} are waiting for your orders",
  "Un {0} attend vos ordres": "A {0} is waiting for your orders",
  "Technologie terminée": "Research complete",
  "Bienvenue dans l'{0} !": "Welcome to the {0}!",
  "L'adversaire atteint l'{0}": "The opponent has reached the {0}",
  "Vous êtes attaqué ! Touchez pour voir où": "You are under attack! Tap to see where",
  "Votre bâtiment principal est tombé : vos troupes se battent encore, votre allié tient": "Your main building has fallen: your troops fight on, and your ally is holding",
  "Votre allié a perdu son bâtiment principal": "Your ally has lost their main building",
  "Un adversaire est hors de combat": "One opponent is out of the fight",
  "Position prise !": "Point captured!",
  "Position perdue ! Touchez pour voir où": "Point lost! Tap to see where",
  "L’adversaire prend une position": "The opponent captures a point",
  "Partie d’essai : elle ne compte ni au classement ni au palmarès.": "Trial game: it counts toward neither your ranking nor your record.",

  // --- js/main.js : les ordres au doigt ---
  "Point de ralliement défini": "Rally point set",
  "{0} unité(s) se mettent à l'abri": "{0} unit(s) taking shelter",
  "Touchez un {0} ou une tour": "Tap a {0} or a tower",
  "Double tap sur le bâtiment pour le sélectionner": "Double tap the building to select it",
  "Soin lancé — double tap sur l’unité pour la sélectionner": "Healing started — double tap the unit to select it",
  "arbres": "trees",
  "filons": "gold veins",
  "sources de nourriture": "food sources",
  "{0} {1} répartis sur {2} {3}": "{0} {1} spread over {2} {3}",
  "{0} {1} envoyé{2} récolter": "{0} {1} sent to gather",
  "{0} ouvriers envoyés à la réparation": "{0} workers sent to repair",
  "{0} ouvriers envoyés sur le chantier": "{0} workers sent to the site",
  "Ouvrier envoyé à la réparation": "Worker sent to repair",
  "Ouvrier envoyé sur le chantier": "Worker sent to the site",
  "{0} : abattage, {1} de nourriture": "{0}: slaughter, {1} food",
  "Chasse au {0} : {1} de nourriture": "Hunting the {0}: {1} food",
  "Aucun soldat pour l’instant": "No soldiers yet",
  "Vos soldats sont à l’abri : « Libérer » les fait sortir": "Your soldiers are sheltered: “Release” lets them out",
  "{0} {1} à l'abri — {2} sans place": "{0} {1} sheltered — {2} left without room",
  "{0} {1} à l'abri": "{0} {1} sheltered",
  "{0} {1} {2} au travail": "{0} {1} {2} back to work",
  "retourne|retournent": { one: "goes", other: "go" },
  "Abris pleins": "Shelters full",
  "Aucun {0} à abriter": "No {0} to shelter",
  "Aucun abri disponible": "No shelter available",
  "Touchez la zone à attaquer": "Tap the area to attack",
  "Touchez le point de ralliement": "Tap the rally point",
  "Touchez le {0} ou la tour où s’abriter": "Tap the {0} or the tower to shelter in",

  // --- js/main.js : la construction ---
  "{0} : touchez l'emplacement (2 doigts pour déplacer la vue)": "{0}: tap where to build (2 fingers to move the view)",
  "Emplacement impossible ici": "Can’t build here",
  "ouvrier|ouvriers": { one: "worker", other: "workers" },
  "{0} ajouté{1} à la file — {2} {3}": "{0} added to the queue — {2} {3}",
  "{0} lancé{1} — {2} {3}": "{0} started — {2} {3}",
  "Ce chantier seul vous tient en jeu : l’annuler, c’est perdre la partie. Touchez « Confirmer » pour l’annuler.": "This site alone keeps you in the game: canceling it means losing. Tap “Confirm” to cancel it.",
  "Chantier annulé, ressources rendues": "Site canceled, resources refunded",
  "Votre dernier {0} : le détruire, c’est perdre la partie. Touchez « Confirmer » pour le raser.": "Your last {0}: destroying it means losing the game. Tap “Confirm” to raze it.",
  "bâtiment militaire": "military building",
  "Touchez « Confirmer » pour raser : {0}.": "Tap “Confirm” to raze: {0}.",
  "{0} unité(s) sortie(s)": "{0} unit(s) out",
  "file remboursée": "queue refunded",
  "{0} détruit{1}{2}": "{0} destroyed{2}",
  "Passage à l’âge suivant lancé…": "Advancing to the next age…",

  // --- js/main.js : les ouvriers ---
  "Aucun {0} à ce poste": "No {0} on this job",
  "Aucun {0} disponible": "No {0} available",
  "nourriture": "food",
  "bois": "wood",
  "or": "gold",
  "Plus de {0} à portée — construisez une ferme ou explorez": "No more {0} within reach — build a farm or explore",
  "Aucun chantier en cours — posez un bâtiment d’abord": "No site underway — place a building first",
  "Aucun {0} ne peut rejoindre le chantier": "No {0} can reach the site",
  "Ouvrier envoyé — {0} {1} sur ce chantier": "Worker sent — {0} {1} on this site",
  "Réaffectation automatique activée": "Automatic reassignment on",
  "Réaffectation manuelle : vos {0} attendront vos ordres": "Manual reassignment: your {0} will wait for your orders",
  "Aucun {0} inactif": "No idle {0}",

  // --- js/main.js : l'allié, la sauvegarde, le style, la vitesse ---
  "Votre allié est hors de combat": "Your ally is out of the fight",
  "Touchez l’endroit que votre allié doit attaquer": "Tap where your ally should attack",
  "Votre allié reprend sa conduite": "Your ally is back on its own plan",
  "Sauvegarde impossible sur cet appareil : la partie ne pourra pas être reprise": "Can’t save on this device: this game can’t be resumed later",
  "Personnages : tes modèles 3D animés": "Characters: your animated 3D models",
  "Personnages : marche dessinée": "Characters: hand-drawn walk",
  "Personnages : illustration peinte": "Characters: painted illustration",
  "{0} : chevalier d’essai rendu à l’avance": "{0}: test knight, pre-rendered",
  "{0} : chevalier d’essai animé en direct": "{0}: test knight, animated live",
  "Style : rien ne change, les troupes de cette partie n’ont que leur modèle 3D": "Style: nothing changes, the troops in this game only have their 3D model",
  "Style : seules les troupes des {0} changent, les tiennes n’ont que leur modèle 3D": "Style: only the troops of the {0} change, yours only have their 3D model",
  "3D en direct : WebGL indisponible ici — le rendu précalculé le remplace": "Live 3D: WebGL unavailable here — the pre-rendered version takes over",
  "Vitesse : {0} ({1})": "Speed: {0} ({1})",
  "Personnages 3D allégés faute de mémoire ({0})": "3D characters scaled down for lack of memory ({0})",
  "Tes personnages 3D sont prêts": "Your 3D characters are ready",
  "Personnages 3D indisponibles ici ({0}) : dessins à la place": "3D characters unavailable here ({0}): drawings instead",

  // --- js/main.js : l'accueil (le palmarès ; le reste est aussi dans le cahier « accueil ») ---
  "{0}, {1} : {2}": "{0}, {1}: {2}",
  "Classée · {0}": "Ranked · {0}",
  "Libre · {0}": "Free play · {0}",
  "Effacer la partie en cours ?": "Erase the game in progress?",
  "Nouvelle partie": "New game",
  "Jouer": "Play",
  "reste {0}": "{0} left",
  "Reprendre la partie": "Resume game",
  "{0} contre {1}": "{0} vs {1}",
  "Partie classée : la quitter compte comme une défaite.": "Ranked game: leaving it counts as a defeat.",
  "Abandonner cette partie": "Abandon this game",
  "Classée": "Ranked",
  "Elo, ligues et coffres": "Elo, leagues and chests",
  "Libre": "Free play",
  "Tu règles l’adversaire": "You set the opponent",
  "Le jeu fonctionne sans connexion. Ta progression est gardée sur cet appareil.": "The game works offline. Your progress is kept on this device.",

  // --- js/game.js : les camps ---
  "Vous": "You",
  "Adversaire": "Opponent",
  "Allié{0}": "Ally{0}",
  "Adversaire {0}": "Opponent {0}",

  // --- js/game.js : ce que la partie dit au joueur ---
  "Cochon capturé : menez-le au village, un {0} l’abattra.": "Pig captured: lead it to the village, and a {0} will slaughter it.",
  "Votre {0} a touché vos propres troupes.": "Your {0} hit your own troops.",
  "Ferme épuisée — reconstruisez-la pour continuer.": "Farm exhausted — rebuild it to keep going.",
  "{0} perdu{1} ! Rebâtissez {2} {3} : il ne vous reste que vos bâtiments militaires.": "{0} lost! Rebuild one: only your military buildings are left.",
  "{0} perdu{1} ! Plus aucun {2} pour rebâtir : il ne vous reste que vos troupes et vos bâtiments militaires.": "{0} lost! No {2} left to rebuild it: only your troops and military buildings are left.",
  "Population maximale atteinte — construisez des maisons.": "Population limit reached — build houses.",
  "Passage d’âge interrompu : votre {0} est tombé.": "Age advance interrupted: your {0} has fallen.",
  "Emplacement impossible ici.": "Can’t build here.",
  "Ressources insuffisantes.": "Not enough resources.",
  "Ce bâtiment n’abrite personne.": "This building can’t shelter anyone.",
  "Bâtiment plein.": "Building full.",
  "Ces unités ne peuvent pas s’y abriter.": "These units can’t shelter there.",

  // --- js/game.js : pourquoi un bouton refuse ---
  "Bâtiment en construction": "Building under construction",
  "Troupe à débloquer": "Troop to unlock",
  "Âge requis : {0}": "Requires the {0}",
  "File d’attente pleine": "Queue full",
  "Ressources insuffisantes": "Not enough resources",
  "Indisponible": "Unavailable",
  "Déjà recherché": "Already researched",
  "Déjà en cours": "Already in progress",
  "Chantier à terminer d’abord : {0}": "Site to finish first: {0}",
  "Il faut {0} bâtiments parmi : {1}": "Requires {0} buildings from: {1}",
  "Il faut encore un bâtiment parmi : {0}": "Requires one more building from: {0}",
  "une {0}": "{0}",
  "un {0}": "{0}",
  "Il faut {0} et {1}": "Requires {0} and {1}",
  "Il faut {0}": "Requires {0}",
  "Âge maximal atteint": "Final age reached",
  "Passage déjà en cours": "Already advancing",
  "Centre-Ville requis": "Town Center required",

  // --- js/ai.js ---
  "L’ennemi prépare une attaque : formez des soldats {0} {1}": "The enemy is preparing an attack: train soldiers at the {1}",

  // --- js/save.js : les incidents, le palmarès ---
  "après {0} min": "after {0} min",
  "après moins d’une minute": "after less than a minute",
  "{0} — {1} Mo d’images, {2} {3}": "{0} — {1} MB of images, {2} {3}",
  "unité|unités": { one: "unit", other: "units" },
  "Le jeu s’est relancé en pleine partie : elle t’attend.": "The game restarted mid-game: your game is waiting for you.",
  "La dernière partie s’est interrompue : elle t’attend.": "Your last game was interrupted: it’s waiting for you.",
  "La page a été rechargée en pleine partie, {0}": "The page reloaded mid-game, {0}",
  "La dernière partie s’est interrompue {0}": "Your last game was interrupted {0}",
  "victoire|victoires": { one: "win", other: "wins" },
  "meilleur temps {0}": "best time {0}",
  "meilleur score {0}": "best score {0}",

  // --- js/sprites.js : les styles des personnages ---
  "Tes modèles animés": "Your animated models",
  "Animé": "Animated",
  "Marche dessinée": "Hand-drawn walk",
  "Peint": "Painted",
  "Illustration réduite": "Scaled-down illustration",
  "3D précalculée": "Pre-rendered 3D",
  "Essai : chevalier rendu à l’avance": "Test: pre-rendered knight",
  "3D en direct": "Live 3D",
  "Essai : chevalier animé en jeu": "Test: knight animated in-game",

  // --- js/sprites.js : les modèles 3D, nommés quand l'un échoue ou est allégé ---
  "ouvrier": "worker",
  "chevalier": "foot knight",
  "homme-poisson": "fish-man",
  "archer": "archer",
  "hydre": "hydra",
  "lancier": "spearman",
  "prêtresse": "priestess",
  "cavalier": "knight",
  "éclaireur": "scout",
  "champion": "champion",
  "bélier": "battering ram",
  "catapulte": "catapult",
  "arbalétrier": "crossbowman",
  "archer monté": "horse archer",
  "pavoisier": "shield bearer",
  "frondeur": "slinger",
  "sapeur": "sapper",
  "{0} solarien": "Solarian {0}",
  "{0} : {1}": "{0}: {1}",
  " ; ": "; ",

  // --- js/modele3d.js : pourquoi un modèle 3D n'a pas pu se préparer ---
  "animation « {0} » absente de {1}": "animation “{0}” missing from {1}",
  "mémoire graphique saturée (toile de réduction refusée)": "out of graphics memory (downscaling canvas refused)",
  "mémoire graphique saturée (toile de travail refusée)": "out of graphics memory (work canvas refused)",
  "mémoire graphique saturée (contexte WebGL perdu)": "out of graphics memory (WebGL context lost)",
  "modèle invisible à la caméra": "model not visible to the camera",
  "mémoire graphique saturée (atlas refusé)": "out of graphics memory (atlas refused)",
};
