// English — la progression et la boutique : le bandeau de l'accueil, les ligues,
// les coffres et leur ouverture, les probabilités, les troupes et leur fiche,
// la boutique et les achats, la confidentialité, la fin d'une partie classée
// (js/progression-ecrans.js), et les noms de la table js/progression-config.js.
// La clé est la phrase française, ses trous notés {0}, {1}… (voir js/langue.js).
// Un mot qui s'accorde avec un nombre a ses formes sous la clé « un|plusieurs ».
export default {
  // --- Les aides : nombres, durées, prix, nom d'une ligue dans une phrase ---
  "{0} %": "{0}%",
  "{0} €": "€{0}",
  "{0} j": "{0} d",
  "{0} h": "{0} h",
  "{0} min": "{0} min",
  // (« ligue de Bronze », « ligue d’Or », « ligue du Soleil » : {0} est l'article, que l'anglais laisse de côté.)
  "ligue {0}{1}": "{1} League",
  "Couronne|Couronnes": { one: "Crown", other: "Crowns" },
  "Éclat|Éclats": { one: "Shard", other: "Shards" },
  "fragment|fragments": { one: "fragment", other: "fragments" },
  "tirage|tirages": { one: "draw", other: "draws" },
  "fragment commun|fragments communs": { one: "common fragment", other: "common fragments" },
  "rare|rares": { one: "rare", other: "rare" },
  "épique|épiques": { one: "epic", other: "epic" },

  // --- La table : ligues, catégories et raretés, coffres et tirages, lots de Couronnes ---
  "Bois": "Wood",
  "Pierre": "Stone",
  "Bronze": "Bronze",
  "Fer": "Iron",
  "Argent": "Silver",
  "Or": "Gold",
  "Cristal": "Crystal",
  "Orichalque": "Orichalcum",
  "Soleil": "Sun",
  "Légendes": "Legends",
  "Commune": "Common",
  "Commun": "Common",
  "Rare": "Rare",
  "Épique": "Epic",
  "Coffre de bois": "Wooden Chest",
  "Coffre d’argent": "Silver Chest",
  "Coffre d’or": "Golden Chest",
  "Coffre légendaire": "Legendary Chest",
  "Tirages ordinaires": "Standard draws",
  "Tirage « rare ou mieux »": "“Rare or better” draw",
  "Tirages épiques": "Epic draws",
  "Poignée": "Handful",
  "Bourse": "Pouch",
  "Coffret": "Strongbox",
  "Trésor": "Treasure",
  "Butin royal": "Royal Hoard",

  // --- D'où vient un coffre ---
  "Victoire": "Victory",
  "Défaite": "Defeat",
  "Égalité": "Tie",
  "Promotion": "Promotion",
  "Semaine jouée": "Week played",
  "Fin de saison": "End of season",
  "Route de saison": "Season road",
  "Points de bataille": "Battle points",

  // --- Le bandeau de l'accueil, la tête des écrans ---
  "Voir les ligues": "View leagues",
  "{0} à {1}": "{0} at {1}",
  "la plus haute ligue": "the highest league",
  "Coffres": "Chests",
  "Troupes": "Troops",
  "Album": "Album",
  "Saison": "Season",
  "Boutique": "Shop",
  "Retour": "Back",
  "Fermer": "Close",

  // --- Les ligues ---
  "Les ligues": "Leagues",
  "Une victoire classée rapporte {0} points, une défaite en coûte {1}.": "A ranked win earns {0} points, a loss costs {1}.",
  "De ligue en ligue, tes troupes jouent à un niveau plus haut en partie classée.": "League after league, your troops play at a higher level in ranked games.",
  "dès {0} Elo": "from {0} Elo",
  "le départ": "the start",
  "troupes jusqu’au niveau {0}": "troops up to level {0}",
  "Reçu : {0}": "Received: {0}",
  "À gagner : {0}": "To win: {0}",
  "titre « {0} »": "title “{0}”",
  "{0} Couronnes": "{0} Crowns",
  "Tu es ici": "You are here",

  // --- Les coffres ---
  "Probabilités": "Odds",
  "Ouvrir": "Open",
  "Aucun coffre à ouvrir. Chaque partie classée en donne un.": "No chests to open. Every ranked game gives one.",
  "Un coffre par partie": "One chest per game",
  "Chaque partie classée donne un coffre, gagnée ou perdue. Son rang est tiré au sort : la victoire a de meilleures chances.": "Every ranked game gives a chest, win or lose. Its rank is drawn at random: a win has better odds.",
  "En {0}": "In {0}",
  "Une partie de {0} minutes, deux fois plus courte : le coffre est un cran en dessous.": "A {0}-minute game, half as long: the chest is one notch lower.",
  "Une défaite de moins de {0} minutes, abandon compris, ne donne pas de coffre.": "A defeat in under {0} minutes, forfeits included, gives no chest.",
  "En plus": "Extras",
  "gagné cette semaine": "earned this week",
  "en jouant {0} jours dans la semaine · {1} sur {2}": "for playing {0} days in a week · {1} of {2}",
  "Un coffre à chaque nouvelle ligue": "A chest at every new league",
  "voir la route des ligues": "see the league road",
  "Contenu et chances de chaque coffre": "Contents and odds of each chest",
  // (Le rang d'un coffre, sans le mot « coffre », sous son image.)
  "bois": "wooden",
  "argent": "silver",
  "or": "golden",
  "légendaire": "legendary",

  // --- Les probabilités d'un coffre ---
  "{0}. Sur 100 coffres, en moyenne : {1},\n      {2}, {3}.": "{0}. Per 100 chests, on average: {1}, {2}, {3}.",
  "Catégorie": "Category",
  "Chance": "Chance",
  "Fragments": "Fragments",
  "Total": "Total",
  "Autocollants — {0} tirages": "Stickers — {0} draws",
  "Autocollant — 1 tirage": "Sticker — 1 draw",
  "Rareté": "Rarity",
  "Un doublon rend": "A duplicate gives",
  "Dans la rareté tirée, chaque autocollant des collections des coffres a la même chance. Et dans chaque {0} : {1} Éclats, toujours.": "Within the rarity drawn, every sticker from the chest collections has the same chance. And in every {0}: {1} Shards, always.",
  "Comment un tirage se fait": "How a draw works",
  "Il choisit une catégorie selon le tableau.": "It picks a category according to the table.",
  "Dans cette catégorie, il choisit à chances égales une de tes troupes débloquées qui n’est pas au niveau maximum.": "In that category, it picks, with equal odds, one of your unlocked troops that is not at max level.",
  "Il donne le nombre de fragments indiqué, toujours le même.": "It gives the number of fragments shown, always the same.",
  "Si tu n’as aucune troupe disponible dans la catégorie, le tirage passe à une autre : celle du dessous d’abord, sinon celle du dessus.": "If you have no troop available in the category, the draw moves to another one: the one below first, otherwise the one above.",
  "Si toutes tes troupes sont au niveau maximum, les fragments deviennent des Éclats.": "If all your troops are at max level, the fragments become Shards.",
  "Aucun coffre ne se vend.": "No chest is ever sold.",

  // --- L'ouverture d'un coffre ---
  "Éclats": "Shards",
  "garanti": "guaranteed",
  "Tu peux améliorer : {0}": "You can upgrade: {0}",
  "Coffre suivant ({0})": "Next chest ({0})",
  "Mes troupes": "My troops",
  "Mon album": "My album",

  // --- Les troupes, la fiche d'une troupe ---
  "niveau maximum": "max level",
  "Niv. {0}": "Lv. {0}",
  "Les fragments des coffres montent le niveau d’une troupe. En partie classée, ta {0} fait jouer les troupes jusqu’au niveau {1}.": "Chest fragments raise a troop’s level. In ranked games, {0} lets troops play up to level {1}.",
  "Points de vie": "Hit points",
  "Dégâts": "Damage",
  "Soin par geste": "Healing per cast",
  "Vue, en cases": "Sight, in tiles",
  "Vivres ou or par minute": "Food or gold per minute",
  "Bois par minute": "Wood per minute",
  "Chargement": "Carrying capacity",
  "Vitesse de chantier": "Build speed",
  "Contre la cavalerie": "Against cavalry",
  "Contre les bâtiments": "Against buildings",
  "Toucher encore : la partie en cours sera effacée": "Tap again: the game in progress will be erased",
  "Essayer en partie libre": "Try it in free play",
  "Trois t’attendent près de ton centre. Une partie d’essai ne compte ni au classement ni au palmarès.": "Three are waiting near your main building. A trial game counts neither for ranking nor for your record.",
  "Tout de suite à la boutique : {0}": "Right now in the shop: {0}",
  "Offerte en {0}, ou après {1} parties classées jouées\n      (tu en as joué {2}).": "Free in {0}, or after {1} ranked games played (you have played {2}).",
  "Niveau maximum atteint.": "Max level reached.",
  "{0} sur {1}": "{0} out of {1}",
  "Passer au niveau {0}": "Upgrade to level {0}",
  "<b>Niveau {0}</b> sur {1}": "<b>Level {0}</b> of {1}",
  "À débloquer": "Locked",
  "Niveau {0}": "Level {0}",
  "En partie classée, elle joue au niveau {0} tant que tu es en {1}. Contre l’ordinateur en partie libre, elle joue à son niveau réel.": "In ranked games, it plays at level {0} as long as you are in {1}. Against the computer in free play, it plays at its real level.",
  "{0} passe au niveau {1}.": "{0} moves up to level {1}.",
  "Sauvegarde impossible sur cet appareil : ce niveau ne sera pas retenu.": "Could not save on this device: this level will not be kept.",

  // --- La boutique ---
  "Toucher encore : {0}": "Tap again: {0}",
  "Toucher encore": "Tap again",
  "En cours…": "In progress…",
  "Offres du moment": "Current offers",
  "Offre de ligue : {0} à moitié prix": "League offer: {0} at half price",
  "{0} au lieu de <s>{1}</s> · encore {2}": "{0} instead of <s>{1}</s> · {2} left",
  "Offre de bienvenue : {0}": "Welcome offer: {0}",
  "{0}, une seule fois · encore {1}": "{0}, one time only · {1} left",
  "Achat simulé : aucun paiement.": "Simulated purchase: no payment.",
  "Bientôt": "Soon",
  "Débloquée": "Unlocked",
  "Voir la fiche : {0}": "View details: {0}",
  "Déjà à toi.": "Already yours.",
  "Sinon offerte en {0}": "Otherwise free in {0}",
  "Une troupe avancée s’obtient gratuitement par sa ligue. Ici, tu l’as tout de suite : c’est la même troupe.": "An advanced troop is free through its league. Here, you get it right away: it’s the same troop.",
  "Toutes les troupes ({0})": "All troops ({0})",
  "au lieu de <s>{0}</s>": "instead of <s>{0}</s>",
  "Couronnes": "Crowns",
  "{0} : {1} Couronnes": "{0}: {1} Crowns",
  "{0} % de plus que le premier lot": "{0}% more than the first pack",
  "Le premier lot": "The first pack",
  "Elles se gagnent en jouant : {0} à chaque nouvelle ligue, et sur la route de la saison.": "You earn them by playing: {0} at every new league, and on the season road.",
  "L’achat de Couronnes arrivera avec l’application. D’ici là, elles se gagnent : {0} à chaque nouvelle ligue, et sur la route de la saison.": "Buying Crowns will come with the app. Until then, you earn them: {0} at every new league, and on the season road.",
  "L’achat de Couronnes arrivera avec l’application. Ici, toucher un lot simule son achat : aucun paiement n’est demandé.": "Buying Crowns will come with the app. Here, tapping a pack simulates its purchase: no payment is requested.",
  "Les Couronnes servent ici, et seulement ici. Le paiement passe par le magasin d’applications.": "Crowns are used here, and only here. Payment goes through the app store.",
  "Restaurer mes achats": "Restore my purchases",
  "Porte-monnaie d’essai : +{0} Couronnes": "Trial wallet: +{0} Crowns",
  "Version d’essai : ce bouton sert à essayer la boutique, il disparaîtra avec l’arrivée des vrais achats.": "Trial version: this button is for trying out the shop; it will go away when real purchases arrive.",
  "Les Couronnes s’achètent.": "Crowns can be bought.",
  "Les Couronnes se gagnent aux ligues et sur la route de la saison.": "Crowns are earned through leagues and on the season road.",
  "Les Éclats se gagnent en jouant : dans chaque coffre, et pour chaque autocollant en double.": "Shards are earned by playing: in every chest, and for every duplicate sticker.",
  "Rien d’aléatoire ne se vend ici : ni coffre, ni fragment, ni niveau.": "Nothing random is sold here: no chests, no fragments, no levels.",

  // --- Ce que la boutique dit d'un achat ---
  "Il te manque {0} pour cet achat.": "You are {0} short for this purchase.",
  "{0} : c’est débloqué. À former dès ta prochaine partie.": "{0}: unlocked. Ready to train in your next game.",
  "Sauvegarde impossible sur cet appareil : cet achat ne sera pas retenu.": "Could not save on this device: this purchase will not be kept.",
  "Version d’essai : cet achat est simulé, aucun paiement n’est demandé.": "Trial version: this purchase is simulated, no payment is requested.",
  "Achat en cours…": "Purchase in progress…",
  "Un achat est déjà en cours.": "A purchase is already in progress.",
  "{0} : c’est débloqué.": "{0}: unlocked.",
  "{0} de plus dans ta bourse.": "{0} more in your purse.",
  "C’est livré.": "Delivered.",
  "Achat en attente : il sera livré dès que le magasin l’aura confirmé.": "Purchase pending: it will be delivered as soon as the store confirms it.",
  "Cet achat t’avait déjà été livré.": "This purchase had already been delivered to you.",
  "Sauvegarde impossible sur cet appareil : l’achat sera livré au prochain lancement.": "Could not save on this device: the purchase will be delivered at the next launch.",
  "L’achat n’a pas abouti. Si un paiement est parti, il sera livré au prochain lancement.": "The purchase did not go through. If a payment was made, it will be delivered at the next launch.",
  "Recherche de tes achats…": "Looking for your purchases…",
  "Le magasin n’a pas répondu. Réessaie dans un moment.": "The store did not respond. Try again in a moment.",
  "{0} : c’est de nouveau à toi.": "{0}: yours again.",
  "Rien à restaurer : tout ce que tu as acheté est déjà là.": "Nothing to restore: everything you bought is already here.",

  // --- Confidentialité, données et mentions ---
  "Confidentialité": "Privacy",
  "Ce que le jeu garde": "What the game keeps",
  "Ta progression (classement, coffres, troupes, collections), ta partie en cours et tes réglages sont gardés <b>sur cet appareil</b>.": "Your progress (ranking, chests, troops, collections), your game in progress and your settings are kept <b>on this device</b>.",
  "Sur cette page web, ta progression est aussi rangée avec ton compte, là où la page le permet, pour la retrouver si le navigateur l’efface.": "On this web page, your progress is also stored with your account, where the page allows it, so you can get it back if the browser erases it.",
  "Ce que le jeu ne fait pas": "What the game does not do",
  "Aucun compte à créer, aucune donnée personnelle demandée.": "No account to create, no personal data requested.",
  "Aucune publicité, aucun traceur, aucune mesure d’audience.": "No ads, no trackers, no analytics.",
  "Aucune donnée ne quitte ton appareil : le jeu fonctionne sans connexion.": "No data leaves your device: the game works offline.",
  "Rien n’est envoyé à un serveur de jeu : une fois chargé, le jeu fonctionne sans connexion.": "Nothing is sent to a game server: once loaded, the game works offline.",
  "Effacer mes données": "Erase my data",
  "Tout repart de zéro : classement, coffres, troupes, collections, monnaies, partie en cours, réglages. C’est définitif.": "Everything starts over from scratch: ranking, chests, troops, collections, currencies, game in progress, settings. This cannot be undone.",
  "Toucher encore : tout effacer, pour de bon": "Tap again: erase everything, for good",
  "Effacer toutes mes données": "Erase all my data",
  "Effacement impossible sur cet appareil : le stockage est fermé.": "Cannot erase on this device: storage is unavailable.",
  "Tes données sont effacées. Le jeu repart de zéro.": "Your data has been erased. The game starts over from scratch.",
  "Éditeur": "Publisher",
  "{0} est édité par <b>{1}</b>.": "{0} is published by <b>{1}</b>.",
  "Pour toute question : {0}.": "For any questions: {0}.",
  "Licences": "Licenses",
  "Pictogrammes : {0}, licence {1}.": "Icons: {0}, {1} license.",
  "Caractères « Lilita One » (Juan Montoreano) et « Nunito » (The Nunito Project Authors) : licence SIL OFL 1.1.": "Typefaces “Lilita One” (Juan Montoreano) and “Nunito” (The Nunito Project Authors): SIL OFL 1.1 license.",
  "Rendu 3D : three.js, licence MIT.": "3D rendering: three.js, MIT license.",
  "Bruitages (Kenney) et musiques (RandomMind, Emma_MA) : domaine public, CC0.": "Sound effects (Kenney) and music (RandomMind, Emma_MA): public domain, CC0.",
  "Illustrations, modèles et autocollants : créés pour le jeu par son auteur.": "Illustrations, models and stickers: created for the game by its author.",

  // --- La langue (les mêmes phrases que le cahier « accueil » : doublons à régler à l'assemblage) ---
  "Langue": "Language",
  "Traduction en cours : certains écrans sont encore en français.": "Translation in progress: some screens are still in French.",
  "Choisie": "Selected",
  "Le jeu redémarre pour changer de langue. Ta partie en cours est gardée.": "The game restarts to change language. Your game in progress is kept.",
  "Changement impossible sur cet appareil : le stockage est fermé.": "Cannot change it on this device: storage is unavailable.",

  // --- La fin d'une partie classée ---
  "Cette partie a déjà été comptée au classement.": "This game has already been counted in the ranking.",
  "Partie annulée : elle ne compte pas au classement.": "Game canceled: it does not count for ranking.",
  "Promotion en <b>{0}</b> : tes troupes y jouent jusqu’au niveau {1}.": "Promoted to <b>{0}</b>: your troops play up to level {1} there.",
  "Retour en {0}.": "Back to {0}.",
  "Nouvelle troupe : <b>{0}</b>": "New troop: <b>{0}</b>",
  "{0} monte au niveau {1}, comme la ligue.": "{0} rises to level {1}, like the league.",
  "+{0} Couronnes pour ta nouvelle ligue.": "+{0} Crowns for your new league.",
  "Cadeau de ligue : <b>{0}</b>": "League gift: <b>{0}</b>",
  "Gagné : <b>{0}</b>": "Earned: <b>{0}</b>",
  "La saison passée te donne encore : {0}.": "Last season still gives you: {0}.",
  "La saison est finie : au-dessus de {0}, le score se resserre, et le tien repart de {1}.": "The season is over: above {0}, scores are compressed, and yours restarts from {1}.",
  "La saison est finie.": "The season is over.",
  "La saison {0} commence : une nouvelle route t’attend.": "Season {0} begins: a new road awaits you.",
  // ({1} : la parenthèse « (première victoire du jour) », précédée de son espace, ou rien.)
  "<b>+{0}</b> points de saison{1}": "<b>+{0}</b> season points{1}",
  "<b>+{0}</b> points de saison{1} : {2}": "<b>+{0}</b> season points{1}: {2}",
  "(première victoire du jour)": "(first win of the day)",
  "palier {0} à prendre": "tier {0} to claim",
  "Offre de ligue : {0} à moitié prix, {1} h": "League offer: {0} at half price, {1} h",
  "Ouvrir mes {0} coffres": "Open my {0} chests",
  "Ouvrir mon coffre": "Open my chest",
};
