// English — les tables de js/config.js : âges, unités, bâtiments, technologies,
// formats de partie, difficultés, cartes, vitesses, peuples, postures, ressources.
// La clé est le texte français, tel qu'il est écrit dans js/config.js.
export default {
  "Âge Sombre": "Dark Age",
  "Âge Féodal": "Feudal Age",
  "Âge des Châteaux": "Castle Age",
  "Centre-Ville": "Town Center",
  "Forme les villageois, stocke les ressources et permet de passer à l’âge suivant.": "Trains villagers, stores resources and lets you advance to the next age.",
  "Maison": "House",
  "Augmente la population maximale de 5.": "Raises the population limit by 5.",
  "Moulin": "Mill",
  "Dépôt de nourriture. Débloque la construction de fermes.": "Food drop-off. Unlocks farms.",
  "Camp de bûcherons": "Lumber Camp",
  "Dépôt de bois. À construire près des forêts.": "Wood drop-off. Build it near forests.",
  "Camp minier": "Mining Camp",
  "Dépôt d’or. À construire près des filons.": "Gold drop-off. Build it near gold veins.",
  "Ferme": "Farm",
  "Source de nourriture inépuisable tant qu’on la reconstruit.": "An endless source of food, as long as you rebuild it.",
  "Caserne": "Barracks",
  "Forme l’infanterie.": "Trains infantry.",
  "Archerie": "Archery Range",
  "Forme les tireurs : archers, puis arbalétriers et archers montés à l’Âge des Châteaux.": "Trains ranged units: archers, then crossbowmen and horse archers in the Castle Age.",
  "Écurie": "Stable",
  "Forme la cavalerie.": "Trains cavalry.",
  "Atelier de siège": "Siege Workshop",
  "Construit les engins de siège.": "Builds siege engines.",
  "Forge": "Blacksmith",
  "Améliore l’armement et l’armure de toutes vos troupes.": "Upgrades the weapons and armor of all your troops.",
  "Temple de l’Hydre": "Temple of the Hydra",
  "Forme les Prêtresses, qui soignent vos troupes ; à l’Âge des Châteaux, invoque l’Hydre.": "Trains Priestesses, who heal your troops; in the Castle Age, summons the Hydra.",
  "Tour de guet": "Watch Tower",
  "Défense fixe qui tire sur les ennemis à portée.": "A fixed defense that shoots at enemies in range.",
  "Atlantes": "Atlanteans",
  "Peuple de la mer": "People of the sea",
  "Solariens": "Solarians",
  "Peuple du désert": "People of the desert",
  "Fellah": "Fellah",
  "Garde": "Guard",
  "Chacal dressé": "Trained Jackal",
  "Chacals dressés": "Trained Jackals",
  "Méhariste": "Camel Rider",
  "Garde masqué": "Masked Guard",
  "Gardes masqués": "Masked Guards",
  "Prêtre du Soleil": "Sun Priest",
  "Prêtres du Soleil": "Sun Priests",
  "Mercenaire atlante": "Atlantean Mercenary",
  "Mercenaires atlantes": "Atlantean Mercenaries",
  "Sphinx": "Sphinx",
  "Lion à tête de pharaon invoqué au Temple : encaisse comme une escouade et frappe jusqu’à trois ennemis à la fois. Occupe 3 places de population.": "A lion with a pharaoh’s head, summoned at the Temple: it soaks up damage like a whole squad and strikes up to three enemies at once. Takes 3 population slots.",
  "Palais du Soleil": "Palace of the Sun",
  "Forme les fellahs, stocke les ressources et permet de passer à l’âge suivant.": "Trains fellahs, stores resources and lets you advance to the next age.",
  "Grenier": "Granary",
  "Cour des Gardes": "Guards’ Courtyard",
  "Champ de tir": "Shooting Range",
  "Enclos des montures": "Mount Pen",
  "Atelier des engins": "Engine Workshop",
  "Fonderie": "Foundry",
  "Temple du Soleil": "Temple of the Sun",
  "Forme les Prêtres du Soleil, qui soignent vos troupes ; à l’Âge des Châteaux, invoque le Sphinx.": "Trains Sun Priests, who heal your troops; in the Castle Age, summons the Sphinx.",
  "Bleu": "Blue",
  "Turquoise": "Turquoise",
  "Rouge": "Red",
  "Orangé": "Orange",
  "Facile": "Easy",
  "L’adversaire vous laisse 15 minutes pour vous installer (4 min 30 en Express, 3 min en Prise de positions, 1 min 30 en Escarmouche), vous prévient, puis attaque par petits groupes.": "The opponent gives you 15 minutes to settle in (4 min 30 in Express, 3 min in Capture Points, 1 min 30 in Skirmish), warns you, then attacks in small groups.",
  "Normal": "Normal",
  "L’adversaire attaque sans prévenir au bout d’une dizaine de minutes (deux en Express, dès la première en Escarmouche), par vagues de plus en plus grosses.": "The opponent attacks without warning after about ten minutes (two in Express, from the first minute in Skirmish), in bigger and bigger waves.",
  "Difficile": "Hard",
  "L’adversaire récolte plus vite et ses vagues grossissent plus vite ; en Classique, il attaque aussi un peu plus tôt qu’en Normal.": "The opponent gathers faster and its waves grow faster; in Classic, it also attacks a little earlier than on Normal.",
  "Escarmouche": "Skirmish",
  "5 min chrono · toute petite carte · réserves pleines, caserne déjà bâtie · raser le bâtiment principal adverse, sinon le meilleur score": "5 min on the clock · tiny map · full stockpiles, barracks already built · raze the enemy’s main building, otherwise the best score wins",
  "Express": "Express",
  "10 min chrono · départ Féodal · raser le bâtiment principal adverse, sinon le meilleur score": "10 min on the clock · Feudal start · raze the enemy’s main building, otherwise the best score wins",
  "Prise de positions": "Capture Points",
  "10 à 12 min · trois positions à prendre et à tenir · 1 point toutes les 5 s par position, le premier à 200 gagne · raser le bâtiment principal adverse gagne aussi": "10 to 12 min · three points to capture and hold · 1 point every 5 s per point held, first to 200 wins · razing the enemy’s main building wins too",
  "2 contre 2": "2 vs 2",
  "15 à 20 min · vous et un allié contre deux adversaires · une équipe est battue quand ses deux bâtiments principaux sont tombés": "15 to 20 min · you and an ally against two opponents · a team is beaten when both its main buildings have fallen",
  "Classique": "Classic",
  "20 à 30 min · trois âges, victoire par conquête": "20 to 30 min · three ages, victory by conquest",
  "Tranquille": "Relaxed",
  "Pour prendre le temps": "Take your time",
  "Le rythme de référence": "The standard pace",
  "Rapide": "Fast",
  "Une partie plus nerveuse": "A livelier game",
  "Blitz": "Blitz",
  "Tout va deux fois plus vite": "Everything runs twice as fast",
  "Minuscule": "Tiny",
  "Petite": "Small",
  "Moyenne": "Medium",
  "Grande": "Large",
  "Agressif": "Aggressive",
  "Engage tout ennemi en vue et le poursuit loin.": "Attacks any enemy in sight and chases it far.",
  "Défensif": "Defensive",
  "Engage ce qui approche, puis revient à son poste.": "Attacks whatever comes close, then returns to its post.",
  "Position tenue": "Stand Ground",
  "Tenir": "Hold",
  "Ne bouge pas : ne frappe que ce qui entre à portée.": "Does not move: only strikes what comes within range.",
  "Sans attaque": "No Attack",
  "Passif": "Passive",
  "N’attaque jamais de sa propre initiative.": "Never attacks on its own.",
  "Brouette": "Wheelbarrow",
  "Villageois : +15 % de vitesse et +3 de capacité de charge.": "Villagers: +15% speed and +3 carrying capacity.",
  "Armes forgées": "Forging",
  "+1 attaque pour les unités de mêlée.": "+1 attack for melee units.",
  "Flèches barbelées": "Fletching",
  "+1 attaque et +1 portée pour les unités à distance et les tours.": "+1 attack and +1 range for ranged units and towers.",
  "Armure d’écailles": "Scale Armor",
  "+1 armure de mêlée et +1 armure perforante.": "+1 melee armor and +1 pierce armor.",
  "Villageois": "Villager",
  "Récolte, construit et répare. La base de toute économie.": "Gathers, builds and repairs. The backbone of any economy.",
  "Milicien": "Militiaman",
  "Fantassin polyvalent et bon marché.": "A cheap, all-round foot soldier.",
  "Lancier": "Spearman",
  "Redoutable contre la cavalerie et les engins de siège.": "Deadly against cavalry and siege engines.",
  "Atlante": "Atlantean",
  "Homme-poisson au trident, venu de l’Atlantide : robuste, et sa longue arme tient la cavalerie à distance.": "A fish-man with a trident, come from Atlantis: sturdy, and his long weapon keeps cavalry at bay.",
  "Archer": "Archer",
  "Tire à distance. Fragile au corps à corps.": "Shoots from a distance. Fragile in close combat.",
  "Arbalétrier": "Crossbowman",
  "Un carreau lourd, de plus loin que l’archer : il perce l’armure de l’infanterie. Lent à recharger.": "A heavy bolt, from farther than the archer: it pierces infantry armor. Slow to reload.",
  "Archer monté": "Horse Archer",
  "Archers montés": "Horse Archers",
  "Archer à cheval : rapide, il tire puis s’esquive — idéal pour harceler. Craint les lanciers.": "A mounted archer: fast, he shoots then slips away — ideal for harassing. Fears spearmen.",
  "Éclaireur": "Scout",
  "Très rapide et large champ de vision : idéal pour explorer.": "Very fast with a wide field of view: ideal for exploring.",
  "Cavalier": "Knight",
  "Cavalerie lourde. Fonce sur les archers et les villageois.": "Heavy cavalry. Charges down archers and villagers.",
  "Champion": "Champion",
  "Infanterie lourde en armure complète : tient la ligne là où le milicien plie.": "Heavy infantry in full armor: holds the line where the militiaman gives way.",
  "Bélier": "Battering Ram",
  "Démolit les bâtiments. Lent et vulnérable aux lanciers.": "Demolishes buildings. Slow and vulnerable to spearmen.",
  "Hydre": "Hydra",
  "Monstre à sept têtes invoqué au Temple : encaisse comme une escouade et mord jusqu’à trois ennemis à la fois. Occupe 3 places de population.": "A seven-headed monster summoned at the Temple: it soaks up damage like a whole squad and bites up to three enemies at once. Takes 3 population slots.",
  "Prêtresse": "Priestess",
  "Soigne les unités blessées à portée : 8 points de vie toutes les 2 s. Sans défense — gardez-la derrière vos lignes.": "Heals wounded units in range: 8 hit points every 2 s. Defenseless — keep her behind your lines.",
  "Catapulte": "Catapult",
  "Lance des boulets de loin : dégâts de zone, redoutable contre les bâtiments et les troupes à l’arrêt. Un soldat ou un rang en marche l’esquive (pas une colonne profonde), et le boulet blesse aussi vos hommes. Lente, sans défense au corps à corps.": "Hurls stones from afar: area damage, deadly against buildings and troops standing still. A lone soldier or a marching rank dodges it (a deep column does not), and the stone hurts your own men too. Slow, and defenseless in close combat.",
  "Pavoisier": "Shield Bearer",
  "Fantassin au grand bouclier : un mur contre les flèches des archers et des tours. Lent, il frappe peu — cavaliers, champions et catapultes l’enfoncent.": "A foot soldier with a great shield: a wall against the arrows of archers and towers. Slow, he hits lightly — knights, champions and catapults break through him.",
  "Frondeur": "Slinger",
  "Tireur bon marché : ses pierres abattent les archers et les archers montés. Portée courte, et rien pour se défendre au corps à corps.": "A cheap ranged unit: his stones bring down archers and horse archers. Short range, and nothing to defend himself with in close combat.",
  "Sapeur": "Sapper",
  "Rapide, il sape les bâtiments et brise les engins de siège. Très fragile : tout soldat l’abat en quelques coups.": "Fast, he undermines buildings and smashes siege engines. Very fragile: any soldier cuts him down in a few blows.",
  "Cerf": "Deer",
  "Gibier : sa carcasse vaut 140 de nourriture. Envoyez des villageois le chasser — il détale quand on le frappe, puis s’arrête.": "Game: its carcass is worth 140 food. Send villagers to hunt it — it bolts when struck, then stops.",
  "Cochon": "Pig",
  "Approchez un villageois pour le capturer, menez-le au village, puis faites-le abattre par un villageois : 100 de nourriture.": "Bring a villager close to capture it, lead it to the village, then have a villager slaughter it: 100 food.",
  "Nourriture": "Food",
  "Bois": "Wood",
  "Or": "Gold",
  // Les noms qui se comptent : un, plusieurs (voir accordsDesTables dans js/config.js).
  "Villageois|Villageois": { "one": "Villager", "other": "Villagers" },
  "Milicien|Miliciens": { "one": "Militiaman", "other": "Militiamen" },
  "Lancier|Lanciers": { "one": "Spearman", "other": "Spearmen" },
  "Atlante|Atlantes": { "one": "Atlantean", "other": "Atlanteans" },
  "Archer|Archers": { "one": "Archer", "other": "Archers" },
  "Arbalétrier|Arbalétriers": { "one": "Crossbowman", "other": "Crossbowmen" },
  "Archer monté|Archers montés": { "one": "Horse Archer", "other": "Horse Archers" },
  "Éclaireur|Éclaireurs": { "one": "Scout", "other": "Scouts" },
  "Cavalier|Cavaliers": { "one": "Knight", "other": "Knights" },
  "Champion|Champions": { "one": "Champion", "other": "Champions" },
  "Bélier|Béliers": { "one": "Battering Ram", "other": "Battering Rams" },
  "Hydre|Hydres": { "one": "Hydra", "other": "Hydras" },
  "Prêtresse|Prêtresses": { "one": "Priestess", "other": "Priestesses" },
  "Catapulte|Catapultes": { "one": "Catapult", "other": "Catapults" },
  "Pavoisier|Pavoisiers": { "one": "Shield Bearer", "other": "Shield Bearers" },
  "Frondeur|Frondeurs": { "one": "Slinger", "other": "Slingers" },
  "Sapeur|Sapeurs": { "one": "Sapper", "other": "Sappers" },
  "Cerf|Cerfs": { "one": "Deer", "other": "Deer" },
  "Cochon|Cochons": { "one": "Pig", "other": "Pigs" },
  "Fellah|Fellahs": { "one": "Fellah", "other": "Fellahs" },
  "Garde|Gardes": { "one": "Guard", "other": "Guards" },
  "Chacal dressé|Chacals dressés": { "one": "Trained Jackal", "other": "Trained Jackals" },
  "Méhariste|Méharistes": { "one": "Camel Rider", "other": "Camel Riders" },
  "Garde masqué|Gardes masqués": { "one": "Masked Guard", "other": "Masked Guards" },
  "Prêtre du Soleil|Prêtres du Soleil": { "one": "Sun Priest", "other": "Sun Priests" },
  "Mercenaire atlante|Mercenaires atlantes": { "one": "Atlantean Mercenary", "other": "Atlantean Mercenaries" },
  "Sphinx|Sphinx": { "one": "Sphinx", "other": "Sphinxes" },
};
